mybook:VanillaMain2.o PayOff3.o SimpleMC4.o Random1.o Vanilla2.o
				g++ VanillaMain2.o PayOff3.o SimpleMC4.o Random1.o Vanilla2.o -o mybook
PayOff3.o:PayOff3.cpp
				g++ -c PayOff3.cpp -o PayOff3.o
SimpleMC4.o:SimpleMC4.cpp
				g++ -c SimpleMC4.cpp -o SimpleMC4.o
Random1.o:Random1.cpp
				g++ -c Random1.cpp -o Random1.o
Vanilla2.o:Vanilla2.cpp
				g++ -c Vanilla2.cpp -o Vanilla2.o
VanillaMain2.o: VanillaMain2.cpp
				g++ -c VanillaMain2.cpp -o VanillaMain2.o
