mybook:VanillaMain1.o PayOff2.o SimpleMC3.o Random1.o DoubleDigital.o Vanilla1.o
				g++ VanillaMain1.o PayOff2.o SimpleMC3.o Random1.o DoubleDigital.o Vanilla1.o -o mybook
PayOff2.o:PayOff2.cpp
				g++ -c PayOff2.cpp -o PayOff2.o
SimpleMC3.o:SimpleMC3.cpp
				g++ -c SimpleMC3.cpp -o SimpleMC3.o
Random1.o:Random1.cpp
				g++ -c Random1.cpp -o Random1.o
DoubleDigital.o:DoubleDigital.cpp
				g++ -c DoubleDigital.cpp -o DoubleDigital.o
Vanilla1.o:Vanilla1.cpp
				g++ -c Vanilla1.cpp -o Vanilla1.o
VanillaMain1.o: VanillaMain1.cpp
				g++ -c VanillaMain1.cpp -o VanillaMain1.o
